[formatting]
	# align_entries = true
	allowed_blank_lines = 3
	column_width = 160
	compact_inline_tables = true
	indent_entries = true
	indent_string = "\t"
	indent_tables = true
	reorder_arrays = true
	reorder_inline_tables = true
	reorder_keys = true
